include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Recommended Dart rules
    prefer_const_constructors: true
    avoid_print: true
    always_declare_return_types: true
    require_trailing_commas: true
    use_super_parameters: true
    prefer_final_locals: true

    # Riverpod-specific best practices
    # See: https://pub.dev/packages/riverpod_lint
    # TODO: check these rules lateron
    # avoid_manual_providers_as_generated_provider: true
    # avoid_public_notifier_properties: true
    prefer_final_fields: true

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider
    - prefer_final_fields
    - prefer_final_locals
    - always_use_package_imports
